version: '3'

services:
  joshu-springboot-container:
    image: joshu-spring-boot-docker-compose:1
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /data/joshu-springboot-container
    ports:
      - "8080-8100:8080"