apiVersion: v1
kind: Deployment
metadata:
  name: joshu-springboot
spec:
  replicas: 3
  selector:
    matchLabels:
      app: joshu-springboot
  template:
    metadata:
      labels:
        app: joshu-springboot
    spec:
      containers:
        - name: springboot
          image: yogireddy34/joshu-docker-demo:joshu-docker-demo
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: joshu-springboot
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: joshu-springboot
